export const NATURE_OF_BUSINESS_OPTIONS = [
  'Dealers in Jewelry',
  'Car dealers',
  'Dealers in luxury goods',
  'Audit firms',
  'Tax consultants',
  'Clearing and settlement companies',
  'Supermarkets',
  'Casinos, Pool Betting and lottery businesses',
  'Law firms, notaries, and other independent legal practitioners',
  'Accountants and Accounting Firms',
  'Trust and Company Service Providers',
  'Estate Surveyors and Valuers',
  'Dealers in precious stones and metals',
  'Importers and dealers in cars or any other automobiles',
  'Construction companies',
  'Consultants and consulting companies',
  'Hospitality Industry',
  'Real estate agents, Estate developers, Estate Agents and Brokers',
  'Mortgage Brokers',
  'Dealers in mechanized farming equipment and machineries',
  'Practitioners of mechanized farming',
  'Benin Zonal Directorate Database',
];
